# Security configuration for Shopping plugin
# Items listed here cannot be sold in shops or auctioned
#
# Wildcard patterns: Use "*<suffix>" (quoted!) to block all items ending with that suffix
# Example: "*_SPAWN_EGG" blocks all spawn eggs (CREEPER_SPAWN_EGG, ZOMBIE_SPAWN_EGG, etc.)

blacklisted_items:
  
  # Command and structure blocks
  - COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - COMMAND_BLOCK_MINECART
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID
  - JIGSAW
  - BARRIER
  
  # All spawn eggs (using wildcard)
  - "*_SPAWN_EGG"
  
  # Bedrock
  - BEDROCK
  
  # More wildcard examples (must be quoted):
  # - "*_MINECART"      (blocks all minecart types)
  # - "*_BUCKET"        (blocks all buckets)
  # - "*_COMMAND_BLOCK" (blocks all command block types)
  
  # Add more items as needed
  # Use Minecraft material names (uppercase)
  # Find material names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

# Custom message when player tries to sell/auction blacklisted item

blacklist_message: "§cThis item is blacklisted and cannot be sold or auctioned!"