# Security configuration for Shopping plugin
# Items listed here cannot be sold in shops or auctioned

blacklisted_items:
  
  # Command and structure blocks
  - COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - COMMAND_BLOCK_MINECART
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID
  - JIGSAW
  - BARRIER
  
  # Spawn eggs (prevent mob griefing)
  - CREEPER_SPAWN_EGG
  - WITHER_SKELETON_SPAWN_EGG
  - ENDER_DRAGON_SPAWN_EGG
  - WITHER_SPAWN_EGG
  - GHAST_SPAWN_EGG
  - BLAZE_SPAWN_EGG
  
  # Bedrock
  - BEDROCK
  
  # Add more items as needed
  # Use Minecraft material names (uppercase)
  # Find material names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

# Custom message when player tries to sell/auction blacklisted item

blacklist_message: "§cThis item is blacklisted and cannot be sold or auctioned!"